// Hono SSR entry for the web-ssr container (DESIGN application-architecture.md §5).
// Liveness probe at /health; everything else delegates to the RRv7 framework-mode
// request handler. The `./build/server/index.js` import resolves at runtime against
// the Vite-generated bundle (RRv7 plugin output) — it does not exist at TS-compile
// time, hence the @ts-expect-error.
import { serve } from "@hono/node-server";
import { Hono } from "hono";
import { createRequestHandler } from "react-router";

// @ts-expect-error — generated by `vite build` (RRv7 plugin); resolves at runtime in the bundled image.
import * as build from "./build/server/index.js";

const PORT = parseInt(process.env.PORT ?? "3001", 10);
const NODE_ENV = process.env.NODE_ENV ?? "production";

const app = new Hono();

const reactRouterHandler = createRequestHandler(build, NODE_ENV);

// Liveness — matches the agent's /health convention.
app.get("/health", (c) => c.json({ status: "ok" }));

// Everything else is the RRv7 handler.
app.all("*", async (c) => reactRouterHandler(c.req.raw, {}));

serve({ fetch: app.fetch, port: PORT }, (info) => {
  console.log(
    JSON.stringify({ event: "web-ssr.startup", port: info.port, node_env: NODE_ENV }),
  );
});

process.on("SIGTERM", () => process.exit(0));
process.on("SIGINT", () => process.exit(0));
