"""Transform use cases for transform management."""

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ..repositories.transform_record import TransformRecord
from ..repositories.dataset_record import DatasetRecord


async def create_transform(
    db: AsyncSession,
    dataset_id: str,
    name: str,
    condition_json: dict,  # RAQB JSON tree (for UI rehydration)
    condition_sql: str,    # SQL WHERE clause (from frontend RAQB)
    description: str | None = None,
    nl_prompt: str | None = None,
) -> TransformRecord:
    """Create a new transform with condition JSON and SQL.

    Frontend generates condition_sql from condition_json using RAQB.

    Checks for duplicate SQL - if a transform with the same condition_sql already
    exists for this dataset, returns the existing transform instead of creating
    a duplicate.

    Args:
        db: Database session
        dataset_id: Parent dataset ID
        name: Transform name
        condition_json: RAQB JSON tree (for UI rehydration)
        condition_sql: SQL WHERE clause (generated by frontend)
        description: Optional description
        nl_prompt: Optional original NL prompt

    Returns:
        Created or existing TransformRecord
    """
    # Verify dataset exists
    result = await db.execute(select(DatasetRecord).where(DatasetRecord.id == dataset_id))
    dataset_record = result.scalar_one_or_none()
    if not dataset_record:
        raise ValueError("Dataset not found")

    # Check for duplicate SQL
    result = await db.execute(
        select(TransformRecord)
        .where(TransformRecord.dataset_id == dataset_id)
        .where(TransformRecord.condition_sql == condition_sql)
        .order_by(TransformRecord.created_at.asc())
        .limit(1)
    )
    existing_transform = result.scalar_one_or_none()

    if existing_transform:
        return existing_transform

    # Create new transform record
    transform_record = TransformRecord(
        dataset_id=dataset_id,
        name=name,
        description=description,
        condition_json=condition_json,
        condition_sql=condition_sql,
        nl_prompt=nl_prompt,
    )
    db.add(transform_record)
    await db.commit()
    await db.refresh(transform_record)
    return transform_record


async def update_transform(
    db: AsyncSession,
    transform_record: TransformRecord,
    name: str | None = None,
    description: str | None = None,
    condition_json: dict | None = None,
    condition_sql: str | None = None,
    status: str | None = None,
) -> TransformRecord:
    """Update a transform, incrementing version if condition_json changes.

    When updating condition_json, condition_sql must also be provided.

    Args:
        db: Database session
        transform_record: TransformRecord to update
        name: New name (optional)
        description: New description (optional)
        condition_json: New RAQB JSON tree (optional, triggers version increment)
        condition_sql: New SQL WHERE clause (required when condition_json changes)
        status: Transform status ('enabled', 'disabled', 'deleted')

    Returns:
        Updated TransformRecord
    """
    if name is not None:
        transform_record.name = name

    if description is not None:
        transform_record.description = description

    if condition_json is not None:
        transform_record.condition_json = condition_json
        transform_record.condition_sql = condition_sql
        transform_record.version += 1

    if status is not None:
        transform_record.status = status

    await db.commit()
    await db.refresh(transform_record)
    return transform_record
