# <!-- DES-ENFORCEMENT : exempt -->
"""pytest-bdd runner for report-typed-kernel.feature.

All scenarios are tagged @pending and skipped by the default filter
(-m "not pending"). DELIVER unpends one scenario at a time (the roadmap
that schedules them is generated by nw-deliver).
"""
from __future__ import annotations

from pytest_bdd import scenarios

scenarios("report-typed-kernel.feature")
