from app.use_cases.project._dbt.readme import generate_readme


class TestReadme:
    def test_generate_readme_includes_project_name(self):
        output = generate_readme("My Analytics")
        assert "My Analytics" in output

    def test_generate_readme_includes_s3_env_var_names(self):
        output = generate_readme("Test Project")
        assert "S3_BUCKET" in output
        assert "S3_REGION" in output
        assert "S3_ACCESS_KEY_ID" in output
        assert "S3_SECRET_ACCESS_KEY" in output
        assert "S3_ENDPOINT" in output
        assert "S3_URL_STYLE" in output

    def test_generate_readme_includes_dbt_run_command(self):
        output = generate_readme("Test Project")
        assert "dbt run" in output

    def test_generate_readme_includes_attribution(self):
        output = generate_readme("Test Project")
        assert "Generated by Dashboard Chat" in output
