def generate_readme(project_name: str) -> str:
    """Generate README.md for the dbt project."""
    return f"""# {project_name} — dbt Project

> Generated by Dashboard Chat

## Prerequisites

- Python 3.9+
- [dbt-duckdb](https://github.com/duckdb/dbt-duckdb) (`pip install dbt-duckdb`)

## Setup

Set the following environment variables for S3 access:

- `S3_BUCKET` — S3 bucket name containing the source data
- `S3_REGION` — AWS region (default: us-east-1)
- `S3_ACCESS_KEY_ID` — S3 access key
- `S3_SECRET_ACCESS_KEY` — S3 secret key
- `S3_ENDPOINT` — S3 endpoint URL (for MinIO or custom S3-compatible storage)
- `S3_URL_STYLE` — URL style: `path` for MinIO, `vhost` for AWS S3 (default: vhost)

## Usage

```bash
dbt run
```
"""
