// Codegen: emit a Python frozenset mirror of `DOMAIN_EVENT_TYPES` from the Zod
// schema. Replaces the runtime parity test (dc-ora) with a build-time
// guarantee. (Bead dc-qj9.3.1, ADR-014 OQ #3 — Option 1.)
//
// Two modes:
//   write (default)        — overwrite the generated Python file
//   --check                — exit non-zero with a diff if the file is stale
//
// Invoked via `npm run codegen:domain-events` (write) and
// `npm run codegen:domain-events:check` (CI guard).

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { DOMAIN_EVENT_TYPES } from "../domainEvents";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "../../..");
const OUTPUT_PATH = resolve(
  REPO_ROOT,
  "backend/app/use_cases/session/_domain_event_types_generated.py",
);

function render(): string {
  // Sort for deterministic output regardless of schema declaration order.
  const sortedTypes = [...DOMAIN_EVENT_TYPES].sort();

  const lines = [
    '"""Generated by `npm run codegen:domain-events`. DO NOT EDIT BY HAND.',
    "",
    "Source of truth: shared/chat/events.ts:DomainEventSchema (minus the",
    "replay-scope exclusion list in shared/chat/domainEvents.ts). Regenerate",
    "with `npm run codegen:domain-events`; CI guards against drift via",
    "`npm run codegen:domain-events:check`. (Bead dc-qj9.3.1.)",
    '"""',
    "",
    "DOMAIN_EVENT_TYPES: frozenset[str] = frozenset(",
    "    {",
    ...sortedTypes.map((t) => `        "${t}",`),
    "    }",
    ")",
    "",
  ];
  return lines.join("\n");
}

function main(): void {
  const expected = render();
  const checkMode = process.argv.includes("--check");

  if (checkMode) {
    let actual: string;
    try {
      actual = readFileSync(OUTPUT_PATH, "utf8");
    } catch (err) {
      console.error(
        `[codegen:domain-events] generated file is missing: ${relative(REPO_ROOT, OUTPUT_PATH)}`,
      );
      console.error(`  Run: npm run codegen:domain-events`);
      console.error(String(err));
      process.exit(1);
    }
    if (actual !== expected) {
      console.error(
        `[codegen:domain-events] ${relative(REPO_ROOT, OUTPUT_PATH)} is stale.`,
      );
      console.error(`  Run: npm run codegen:domain-events  (and commit)`);
      console.error(`  Source: shared/chat/events.ts:DomainEventSchema`);
      process.exit(1);
    }
    console.log(
      `[codegen:domain-events] ${relative(REPO_ROOT, OUTPUT_PATH)} is up to date.`,
    );
    return;
  }

  writeFileSync(OUTPUT_PATH, expected, "utf8");
  console.log(
    `[codegen:domain-events] wrote ${relative(REPO_ROOT, OUTPUT_PATH)} (${DOMAIN_EVENT_TYPES.size} types).`,
  );
}

main();
