"""Metadata repository package for database persistence.

Provides CRUD operations for projects, datasets, and transforms.
"""

from typing import Any, Protocol

from .assistant_audit_entry import AssistantAuditEntry as AssistantAuditEntry
from .dataset_record import DatasetRecord as DatasetRecord
from .external_access_record import ExternalAccessRecord as ExternalAccessRecord
from .organization_record import OrganizationRecord as OrganizationRecord
from .project_memory_record import ProjectMemoryRecord as ProjectMemoryRecord
from .project_record import ProjectRecord as ProjectRecord
from .query_engine_node_record import QueryEngineNodeRecord as QueryEngineNodeRecord
from .report_record import ReportRecord as ReportRecord
from .session_record import SessionRecord as SessionRecord
from .source_record import SourceRecord as SourceRecord
from .transform_record import TransformRecord as TransformRecord
from .view_record import ViewRecord as ViewRecord


class MetadataRepositoryProtocol(Protocol):
    """Protocol for metadata database operations.

    This protocol defines the interface for all metadata persistence operations.
    Implementations handle the actual database interaction (e.g., SQLAlchemy).
    """

    # -------------------------------------------------------------------------
    # Project operations
    # -------------------------------------------------------------------------

    async def list_projects(self, org_id: str | None = None) -> list[dict[str, Any]]:
        """List all projects ordered by creation date (newest first).

        Args:
            org_id: Optional org ID to filter by.

        Returns:
            List of project dictionaries with id, name, description, timestamps.
        """
        ...

    async def get_project(
        self,
        project_id: str,
    ) -> dict[str, Any] | None:
        """Get a project by ID (metadata only, no datasets).

        Args:
            project_id: Project UUID

        Returns:
            Project dict, or None if not found.
        """
        ...

    async def create_project(
        self,
        name: str,
        description: str | None = None,
        org_id: str | None = None,
        created_by: str | None = None,
    ) -> dict[str, Any]:
        """Create a new project.

        Args:
            name: Project name
            description: Optional description
            org_id: Organization ID for multi-tenancy
            created_by: User ID of creator

        Returns:
            Created project dictionary.
        """
        ...

    async def update_project(
        self,
        project_id: str,
        update_data: dict[str, Any],
    ) -> dict[str, Any] | None:
        """Update a project.

        Args:
            project_id: Project UUID
            update_data: Fields to update (name, description)

        Returns:
            Updated project dict, or None if not found.
        """
        ...

    async def delete_project(self, project_id: str) -> bool:
        """Delete a project and all its datasets.

        Args:
            project_id: Project UUID

        Returns:
            True if deleted, False if not found.
        """
        ...

    # -------------------------------------------------------------------------
    # Dataset operations
    # -------------------------------------------------------------------------

    async def list_datasets(
        self,
        project_id: str | None = None,
        include_transforms: bool = True,
        archived: bool | None = None,
    ) -> "list[DatasetRecord]":
        """List datasets, optionally filtered by project.

        Args:
            project_id: Optional project UUID to filter by
            include_transforms: Whether to eagerly load transforms (default True)
            archived: Cold-storage filter (MR-7). None/False excludes archived rows
                (the live view); True returns only archived rows (the cold-storage list).

        Returns:
            List of DatasetRecord ORM objects.
        """
        ...

    async def get_dataset(
        self,
        dataset_id: str,
        include_transforms: bool = True,
    ) -> dict[str, Any] | None:
        """Get a dataset by ID with optional transforms.

        Args:
            dataset_id: Dataset UUID
            include_transforms: Whether to include transform list

        Returns:
            Dataset dict with transforms, or None if not found.
        """
        ...

    async def create_dataset(
        self,
        project_id: str,
        name: str,
        schema_config: dict[str, Any],
        description: str | None = None,
        partition_fields: list[str] | None = None,
        column_profiles: dict[str, Any] | None = None,
        row_count: int | None = None,
        display_name: str | None = None,
    ) -> dict[str, Any]:
        """Create a new dataset record.

        ID and storage_path are generated by the database (server_default / computed).

        Args:
            project_id: Parent project UUID
            name: Immutable dataset filename (never mutated by an edit)
            schema_config: Field definitions for query builder
            description: Optional description
            partition_fields: List of field names used for partitioning
            column_profiles: Per-column value statistics
            row_count: Total rows snapshotted at ingestion (None for legacy datasets)
            display_name: Editable human label; UI falls back to ``name`` when unset

        Returns:
            Created dataset dictionary.

        Raises:
            ValueError: If project not found.
        """
        ...

    async def update_dataset(
        self,
        dataset_id: str,
        **kwargs: Any,
    ) -> "DatasetRecord":
        """Update a dataset's metadata.

        Args:
            dataset_id: Dataset UUID
            **kwargs: Fields to update (name, description, etc.)

        Returns:
            Updated DatasetRecord with transforms.
        """
        ...

    async def delete_dataset(self, dataset_id: str) -> str | None:
        """Delete a dataset record.

        Args:
            dataset_id: Dataset UUID

        Returns:
            The storage_path of deleted dataset (for file cleanup), or None if not found.
        """
        ...

    async def project_exists(self, project_id: str) -> bool:
        """Check if a project exists.

        Args:
            project_id: Project UUID

        Returns:
            True if project exists.
        """
        ...

    async def dataset_exists(self, dataset_id: str) -> bool:
        """Check if a dataset exists.

        Args:
            dataset_id: Dataset UUID

        Returns:
            True if dataset exists.
        """
        ...

    # -------------------------------------------------------------------------
    # Transform operations
    # -------------------------------------------------------------------------

    async def find_transform_by_sql(
        self,
        dataset_id: str,
        condition_sql: str,
    ) -> dict[str, Any] | None:
        """Find an existing transform with matching SQL.

        Args:
            dataset_id: Parent dataset UUID
            condition_sql: SQL WHERE clause to match

        Returns:
            Transform dict if found, None otherwise.
        """
        ...

    async def create_transform(
        self,
        dataset_id: str,
        name: str,
        condition_json: dict[str, Any],
        condition_sql: str,
        description: str | None = None,
        nl_prompt: str | None = None,
    ) -> dict[str, Any]:
        """Create a new transform.

        Args:
            dataset_id: Parent dataset UUID
            name: Transform name
            condition_json: RAQB JSON tree
            condition_sql: SQL WHERE clause
            description: Optional description
            nl_prompt: Optional original NL prompt

        Returns:
            Created transform dictionary.

        Raises:
            ValueError: If dataset not found.
        """
        ...

    async def update_transform(
        self,
        transform_id: str,
        update_data: dict[str, Any],
    ) -> dict[str, Any] | None:
        """Update a transform.

        If condition_json is updated, version is incremented.

        Args:
            transform_id: Transform UUID
            update_data: Fields to update

        Returns:
            Updated transform dict, or None if not found.
        """
        ...

    async def delete_transform(self, transform_id: str) -> bool:
        """Delete a transform.

        Args:
            transform_id: Transform UUID

        Returns:
            True if deleted, False if not found.
        """
        ...

    # -------------------------------------------------------------------------
    # View operations
    # -------------------------------------------------------------------------

    async def create_view(
        self,
        project_id: str,
        org_id: str,
        name: str,
        sql_definition: str,
        source_refs: list | None = None,
        description: str | None = None,
        materialization: str = "ephemeral",
    ) -> dict[str, Any]:
        """Create a new view."""
        ...

    async def get_view(self, view_id: str) -> dict[str, Any] | None:
        """Get a view by ID."""
        ...

    async def list_views_by_project(self, project_id: str) -> list:
        """List views for a project."""
        ...

    async def update_view(self, view_id: str, **kwargs: Any) -> Any:
        """Update a view."""
        ...

    async def delete_view(self, view_id: str) -> bool:
        """Delete a view."""
        ...

    async def view_exists(self, view_id: str) -> bool:
        """Check if a view exists."""
        ...

    # -------------------------------------------------------------------------
    # Report operations
    # -------------------------------------------------------------------------

    async def create_report(
        self,
        project_id: str,
        org_id: str,
        name: str,
        sql_definition: str,
        report_type: str,
        source_refs: list | None = None,
        description: str | None = None,
        domain: str = "Organization",
        columns_metadata: list | None = None,
        materialization: str = "view",
    ) -> dict[str, Any]:
        """Create a new report."""
        ...

    async def get_report(self, report_id: str) -> dict[str, Any] | None:
        """Get a report by ID."""
        ...

    async def list_reports_by_project(self, project_id: str) -> list:
        """List reports for a project."""
        ...

    async def update_report(self, report_id: str, **kwargs: Any) -> Any:
        """Update a report."""
        ...

    async def delete_report(self, report_id: str) -> bool:
        """Delete a report."""
        ...

    async def report_exists(self, report_id: str) -> bool:
        """Check if a report exists."""
        ...


from .project_repository import ProjectRepository as ProjectRepository  # noqa: E402
from .project_repository import ProjectRepositoryProtocol as ProjectRepositoryProtocol  # noqa: E402
from .repository import MetadataRepository as MetadataRepository  # noqa: E402

__all__ = [
    "MetadataRepository",
    "MetadataRepositoryProtocol",
    "ProjectRepository",
    "ProjectRepositoryProtocol",
]
