from app.use_cases.project.dbt.readme import generate_readme


class TestReadme:
    def test_project_name_appears(self):
        output = generate_readme("My Analytics")
        assert "My Analytics" in output

    def test_env_var_names_appear(self):
        output = generate_readme("Test Project")
        assert "S3_BUCKET" in output
        assert "S3_REGION" in output
        assert "S3_ACCESS_KEY_ID" in output
        assert "S3_SECRET_ACCESS_KEY" in output
        assert "S3_ENDPOINT" in output
        assert "S3_URL_STYLE" in output

    def test_dbt_run_appears(self):
        output = generate_readme("Test Project")
        assert "dbt run" in output

    def test_generated_by_dashboard_chat(self):
        output = generate_readme("Test Project")
        assert "Generated by Dashboard Chat" in output
