from typing import Protocol

from .types import AuthUser


class AuthProvider(Protocol):
    async def verify_token(self, token: str) -> AuthUser: ...
    async def get_login_url(self, redirect_uri: str, *, organization_id: str | None = None) -> tuple[str, str]: ...
    async def handle_callback(self, code: str) -> tuple[AuthUser, str, str, int]: ...
    async def refresh_access_token(self, refresh_token: str) -> tuple[AuthUser, str, str, int]: ...
    async def revoke_session(self, access_token: str) -> None: ...
    async def get_logout_url(self) -> str: ...
    async def reissue_with_org(self, user: AuthUser, org_id: str) -> tuple[str, str, int]: ...
