from typing import Protocol

from .types import AuthUser


class AuthProvider(Protocol):
    async def verify_token(self, token: str) -> AuthUser: ...
    async def get_login_url(self, redirect_uri: str, *, organization_id: str | None = None) -> str: ...
    async def handle_callback(self, code: str) -> tuple[AuthUser, str, str, int]: ...
    async def refresh_access_token(self, refresh_token: str) -> tuple[AuthUser, str, str, int]: ...
    async def get_logout_url(self) -> str: ...
