"""Generated by `npm run codegen:domain-events`. DO NOT EDIT BY HAND.

Source of truth: shared/chat/events.ts:DomainEventSchema (minus the
replay-scope exclusion list in shared/chat/domainEvents.ts). Regenerate
with `npm run codegen:domain-events`; CI guards against drift via
`npm run codegen:domain-events:check`. (Bead dc-qj9.3.1.)
"""

DOMAIN_EVENT_TYPES: frozenset[str] = frozenset(
    {
        "column_renamed",
        "error_occurred",
        "row_added",
        "row_deleted",
        "transform_applied",
        "transform_re_enabled",
        "transform_undone",
        "turn_done",
    }
)
