"""initial schema

Revision ID: 37527f1d9d35
Revises: 
Create Date: 2026-02-22 06:42:31.132025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37527f1d9d35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), server_default=sa.text('(uuidv7())'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_messages',
    sa.Column('id', sa.String(length=36), server_default=sa.text('(uuidv7())'), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False, comment="Type of aggregate (e.g., 'Upload')"),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False, comment='ID of the aggregate instance'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment="Domain event class name (e.g., 'UploadFileReceived')"),
    sa.Column('payload', sa.JSON(), nullable=False, comment='Serialized event data'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False, comment='Whether event has been published to message queue'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='When event was published'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_aggregate_events', 'outbox_messages', ['aggregate_type', 'aggregate_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_outbox_messages_aggregate_id'), 'outbox_messages', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_aggregate_type'), 'outbox_messages', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_outbox_messages_created_at'), 'outbox_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_messages_processed'), 'outbox_messages', ['processed'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), server_default=sa.text('(uuidv7())'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), server_default=sa.text('(uuidv7())'), nullable=False),
    sa.Column('storage_path', sa.String(), sa.Computed("'datasets/' || project_id || '/' || id || '/'", ), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_config', sa.JSON(), nullable=False),
    sa.Column('partition_fields', sa.JSON(), nullable=False),
    sa.Column('column_profiles', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_storage_path'), 'datasets', ['storage_path'], unique=True)
    op.create_table('external_access',
    sa.Column('id', sa.String(length=36), server_default=sa.text('(uuidv7())'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('pg_schema', sa.String(length=255), nullable=False),
    sa.Column('pg_role', sa.String(length=255), nullable=False),
    sa.Column('pg_password_hash', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_external_access_org_id'), 'external_access', ['org_id'], unique=False)
    op.create_table('transforms',
    sa.Column('id', sa.String(length=36), server_default=sa.text('(uuidv7())'), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('condition_sql', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transform_type', sa.String(length=20), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=True),
    sa.Column('expression_sql', sa.Text(), nullable=True),
    sa.Column('expression_config', sa.JSON(), nullable=True),
    sa.Column('nl_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transforms')
    op.drop_index(op.f('ix_external_access_org_id'), table_name='external_access')
    op.drop_table('external_access')
    op.drop_index(op.f('ix_datasets_storage_path'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_outbox_messages_processed'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_created_at'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_aggregate_type'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_aggregate_id'), table_name='outbox_messages')
    op.drop_index('ix_outbox_aggregate_events', table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_table('organizations')
    # ### end Alembic commands ###
