// Node SSR entry for the web-ssr container (ADR-034 / ADR-047).
//
// This is the runtime the `web-ssr` compose service boots. It hosts the RRv7
// framework-mode request handler produced by `react-router build`, so the
// server-side `/ui-server/*` resource routes (health, chat relay, dataset
// mutations, uploads, …) and any SSR route rendering run inside a real Node
// process — a static file server cannot serve them.
//
// It is written against `node:http` and the Web Fetch primitives Node exposes
// globally (Request/Response/Headers/ReadableStream), pulling in NO packages
// beyond `react-router` (already a ui/ dependency). That mirrors
// `app/entry.server.tsx`, which bridges Node streams to a web Response without
// the `@react-router/node` helper: the container stays dependency-honest and
// the pnpm/npm lockfiles need no new entries.
//
// Responsibilities, matching the removed frontend/ssr.ts:
//   1. Liveness probe at GET /health.
//   2. Serve /assets/* statically from build/client — web-ssr is the SINGLE
//      source/owner of the content-hashed frontend bundle (ADR-047), so the
//      same build that emitted the asset URLs serves the files and the hashes
//      can never diverge.
//   3. Delegate everything else to the RRv7 request handler.
import { createReadStream, promises as fs } from "node:fs";
import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { extname, join, normalize } from "node:path";
import { Readable } from "node:stream";

import { createRequestHandler } from "react-router";

// @ts-expect-error — generated by `react-router build` (RRv7 plugin); resolves
// at esbuild-bundle time in the packaged image, not at TS-compile time.
import * as build from "./build/server/index.js";

const PORT = parseInt(process.env.PORT ?? "3001", 10);
const NODE_ENV = process.env.NODE_ENV ?? "production";

// `root` is relative to the container cwd (`/app`, the image workdir); the
// client bundle lives at `/app/ui/build/client`.
const CLIENT_DIR = join(process.cwd(), "ui", "build", "client");

const CONTENT_TYPES: Record<string, string> = {
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".ico": "image/x-icon",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".txt": "text/plain; charset=utf-8",
  ".wasm": "application/wasm",
};

const reactRouterHandler = createRequestHandler(build, NODE_ENV);

/** Translate a Node request into the web `Request` the RRv7 handler expects. */
function toWebRequest(req: IncomingMessage): Request {
  const url = `http://${req.headers.host ?? "localhost"}${req.url ?? "/"}`;
  const headers = new Headers();
  for (const [key, value] of Object.entries(req.headers)) {
    if (value === undefined) continue;
    if (Array.isArray(value)) for (const v of value) headers.append(key, v);
    else headers.set(key, value);
  }
  const method = req.method ?? "GET";
  const hasBody = method !== "GET" && method !== "HEAD";
  return new Request(url, {
    method,
    headers,
    body: hasBody ? (Readable.toWeb(req) as ReadableStream) : undefined,
    // Required when streaming a request body on Node's undici fetch impl.
    ...(hasBody ? { duplex: "half" } : {}),
  } as RequestInit);
}

/** Write a web `Response` back out through the Node response. */
async function sendWebResponse(res: ServerResponse, response: Response): Promise<void> {
  res.statusCode = response.status;
  response.headers.forEach((value, key) => res.setHeader(key, value));
  if (response.body) {
    await new Promise<void>((resolve, reject) => {
      const nodeStream = Readable.fromWeb(response.body as never);
      nodeStream.on("error", reject);
      res.on("error", reject);
      res.on("finish", resolve);
      nodeStream.pipe(res);
    });
  } else {
    res.end();
  }
}

/**
 * Serve a content-hashed asset from build/client. Returns `true` when handled;
 * a miss returns `false` so the request falls through to the RRv7 handler
 * (matching the old Hono `serveStatic` fall-through semantics).
 */
async function tryServeAsset(req: IncomingMessage, res: ServerResponse): Promise<boolean> {
  const pathname = new URL(req.url ?? "/", "http://localhost").pathname;
  // Contain the lookup to build/client — reject any path that escapes it.
  const rel = normalize(decodeURIComponent(pathname)).replace(/^(\.\.[/\\])+/, "");
  const filePath = join(CLIENT_DIR, rel);
  if (!filePath.startsWith(CLIENT_DIR)) return false;
  try {
    const stat = await fs.stat(filePath);
    if (!stat.isFile()) return false;
    res.statusCode = 200;
    res.setHeader("Content-Type", CONTENT_TYPES[extname(filePath)] ?? "application/octet-stream");
    res.setHeader("Content-Length", String(stat.size));
    // Vite emits content-hashed filenames — safe to cache immutably.
    res.setHeader("Cache-Control", "public, max-age=31536000, immutable");
    await new Promise<void>((resolve, reject) => {
      const stream = createReadStream(filePath);
      stream.on("error", reject);
      res.on("error", reject);
      res.on("finish", resolve);
      stream.pipe(res);
    });
    return true;
  } catch {
    return false;
  }
}

const server = createServer((req, res) => {
  void (async () => {
    try {
      const pathname = new URL(req.url ?? "/", "http://localhost").pathname;

      // Liveness — matches the agent's /health convention.
      if (pathname === "/health") {
        res.statusCode = 200;
        res.setHeader("Content-Type", "application/json");
        res.end(JSON.stringify({ status: "ok" }));
        return;
      }

      // Frontend assets — web-ssr owns build/client (ADR-047). Fall through on a
      // miss so a non-asset path under /assets/* still reaches the handler.
      if (pathname.startsWith("/assets/") && (await tryServeAsset(req, res))) return;

      await sendWebResponse(res, await reactRouterHandler(toWebRequest(req), {}));
    } catch (error) {
      console.error(error);
      if (!res.headersSent) res.statusCode = 500;
      res.end("Internal Server Error");
    }
  })();
});

server.listen(PORT, () => {
  // stdout startup banner (console.debug is a stdout alias in Node); ops greps
  // this line to confirm the SSR runtime bound its port.
  console.debug(
    JSON.stringify({ event: "web-ssr.startup", port: PORT, node_env: NODE_ENV }),
  );
});

process.on("SIGTERM", () => process.exit(0));
process.on("SIGINT", () => process.exit(0));
